---
title: "rmaADM"

output:
  github_document:
    toc: true
    toc_depth: 3
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      echo = TRUE,
                        fig.path = "man/figures/")
library(knitr)
library(dplyr)
library(devtools)
load_all()

```

The following table details the helper data sets included in the package. Any of the data sets can be loaded by using the `load_data()` function, for example `load_data("adm_layout")`. 
```{r helper_data, include=FALSE}
  # initialize a dataframe with the columns "dataset","rows","columns","years","description"
  df <- data.frame(dataset = character(),
                   rows = integer(),
                   columns = integer(),
                   years = character(),
                   description = character(),
                   stringsAsFactors = FALSE)
  
  # fill in the dataframe with the dataset names, number of rows, number of columns, years, and description using the files in "./data"
  for(f in list.files("./data", pattern = "\\.rda$")){
    # load the dataset
    load(paste0("./data/", f))
    
    # get the name of the dataset
    name <- gsub("\\.rda$", "", f)
    
    # get the number of rows and columns
    rows <- nrow(get(name))
    columns <- ncol(get(name))
    
    # get the years covered by the dataset
    years <- paste0(min(get(name)$reinsurance_year), "-", max(get(name)$reinsurance_year))
    
    # add a row to the dataframe
    df <- rbind(df, data.frame(dataset = name,
                                rows = rows,
                                columns = columns,
                                years = years,
                                stringsAsFactors = FALSE))
  }


  # define descriptions of the data set
  descriptions_list = list("adm_layout" = "A dataset containing the layout of the ADM data.",
                           "interval" = "A dataset containing info on PRF intervals")

  # merge the descriptions into the dataframe
  df <- df %>%
    left_join(data.frame(dataset = names(descriptions_list),
                         description = unlist(descriptions_list)),
              by = "dataset") %>%
    mutate(description = ifelse(is.na(description), "No description available", description))
  

  

```

```{r, include = TRUE, echo = FALSE}
 knitr::kable(df)
```
